import type { Property, Review } from '@/types'

/** Fallback data when Sanity is not configured */
export const MOCK_PROPERTIES: Property[] = [
  {
    slug: 'queensway-w2-2bed',
    title: 'Bright 2-bedroom flat on Queensway',
    address: { line1: 'Queensway', area: 'Bayswater', postcode: 'W2' },
    listingType: 'lettings',
    status: 'available',
    price: 2400,
    pricePeriod: 'pcm',
    bedrooms: 2,
    bathrooms: 1,
    isFeatured: true,
    tag: 'New listing',
    mainImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=75&auto=format&fit=crop',
  },
  {
    slug: 'redan-place-w2-1bed',
    title: '1-bedroom flat on Redan Place',
    address: { line1: 'Redan Place', area: 'Bayswater', postcode: 'W2' },
    listingType: 'lettings',
    status: 'available',
    price: 1850,
    pricePeriod: 'pcm',
    bedrooms: 1,
    bathrooms: 1,
    isFeatured: true,
    tag: null,
    mainImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=75&auto=format&fit=crop',
  },
  {
    slug: 'hyde-park-gate-3bed',
    title: '3-bedroom flat near Lancaster Gate',
    address: { line1: 'Lancaster Gate', area: 'W2', postcode: 'W2' },
    listingType: 'lettings',
    status: 'available',
    price: 3750,
    pricePeriod: 'pcm',
    bedrooms: 3,
    bathrooms: 2,
    isFeatured: true,
    tag: 'Featured',
    mainImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=75&auto=format&fit=crop',
  },
  {
    slug: 'leinster-gardens-2bed',
    title: '2-bedroom flat on Leinster Gardens',
    address: { line1: 'Leinster Gardens', area: 'W2', postcode: 'W2' },
    listingType: 'lettings',
    status: 'let-agreed',
    price: 2100,
    pricePeriod: 'pcm',
    bedrooms: 2,
    bathrooms: 1,
    isFeatured: false,
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=75&auto=format&fit=crop',
  },
  {
    slug: 'porchester-road-sale',
    title: '2-bedroom flat on Porchester Road',
    address: { line1: 'Porchester Road', area: 'W2', postcode: 'W2' },
    listingType: 'sales',
    status: 'available',
    price: 650000,
    pricePeriod: 'sale',
    bedrooms: 2,
    bathrooms: 1,
    isFeatured: false,
    tag: 'For sale',
    mainImage: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=75&auto=format&fit=crop',
  },
  {
    slug: 'westbourne-grove-1bed',
    title: '1-bedroom flat on Westbourne Grove',
    address: { line1: 'Westbourne Grove', area: 'W2', postcode: 'W2' },
    listingType: 'lettings',
    status: 'available',
    price: 1650,
    pricePeriod: 'pcm',
    bedrooms: 1,
    bathrooms: 1,
    isFeatured: false,
    mainImage: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=75&auto=format&fit=crop',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    author: 'James T.',
    date: '2025-03-01',
    source: 'trustpilot',
    rating: 5,
    text: 'Rupa was fantastic from start to finish. She found us the perfect flat in Bayswater within a week — responsive, professional and genuinely cared about getting us the right place.',
    showOnSite: true,
    isPinned: false,
    sortOrder: 0,
  },
  {
    id: '2',
    author: 'Priya M.',
    date: '2025-01-15',
    source: 'google',
    rating: 5,
    text: "As a landlord I've used many agencies over the years. Uniqletts stand out for their personal approach. Rupa manages everything independently and keeps me informed without chasing.",
    showOnSite: true,
    isPinned: false,
    sortOrder: 1,
  },
  {
    id: '3',
    author: 'Daniel F.',
    date: '2024-11-20',
    source: 'trustpilot',
    rating: 5,
    text: "First time renting alone and Rupa made it completely stress-free. Always available to answer questions and the move-in process was the smoothest I've experienced.",
    showOnSite: true,
    isPinned: false,
    sortOrder: 2,
  },
]
